// Sprite loader. Pre-loads PNGs from /sprites/ and exposes a synchronous
// getter the renderer can call from a hot path. Each sprite is loaded once,
// background-keyed (cream → transparent) for "sprite" type assets, and cached.
//
// Asset naming convention (matches scripts/gen-images.mjs):
//   building-{typeId}.png   — building portraits
//   unit-{typeId}.png       — unit portraits
//   resource-{typeId}.png   — resource icons
//   {scene-key}.png         — full-bleed scene backgrounds

import { UNIT_DEFS } from '@/config/units';
import { BUILDING_DEFS } from '@/config/buildings';
import { asset } from '@/util/assets';

const CACHE = new Map<string, HTMLImageElement | null>();
const KEYED = new Map<string, HTMLCanvasElement | null>();
const TERRAIN = new Map<string, HTMLCanvasElement | null>();

// Campaign bosses/buildings borrow an existing type's sprite set via
// def.spriteBase (e.g. khara draws with subahu's art). Every typeId→key
// mapper resolves through these first.
function unitSpriteType(typeId: string): string {
  return UNIT_DEFS[typeId]?.spriteBase ?? typeId;
}
function buildingSpriteType(typeId: string): string {
  return BUILDING_DEFS[typeId]?.spriteBase ?? typeId;
}

const TILE_BUILDING_KEYS = [
  'tile-town-center', 'tile-lanka-citadel', 'tile-house',
  'tile-lumber-camp', 'tile-mill', 'tile-mining-camp',
  'tile-barracks', 'tile-archery-range', 'tile-stable', 'tile-watchtower',
];

const TERRAIN_KEYS = [
  'terrain-grass',
  'terrain-dirt',
  'terrain-water',
  'terrain-forest-floor',
  'terrain-rock',
];

// 8-direction sprite keys for each unit. Generated by gen-images.mjs:
//   topdown-{unit}-{n|ne|e|se}.png — original `topdown-{unit}.png` is the S facing.
// W, NW, SW are produced at runtime by horizontal-flipping E, NE, SE.
const UNIT_BASES = [
  'villager', 'spearman', 'archer', 'cavalry',
  'rakshasa-villager', 'rakshasa-spear', 'rakshasa-archer', 'rakshasa-cavalry',
];
const UNIT_DIR_SUFFIXES = ['n', 'ne', 'e', 'se'];
const UNIT_DIR_KEYS: string[] = [];
for (const b of UNIT_BASES) {
  for (const s of UNIT_DIR_SUFFIXES) UNIT_DIR_KEYS.push(`topdown-${b}-${s}`);
}

const HERO_BOSS_BASES = ['rama', 'lakshmana', 'tataka', 'subahu', 'maricha', 'grunt_enemy'];
const HERO_BOSS_DIR_KEYS: string[] = [];
for (const b of HERO_BOSS_BASES) {
  HERO_BOSS_DIR_KEYS.push(`topdown-${b}`);
  for (const s of UNIT_DIR_SUFFIXES) HERO_BOSS_DIR_KEYS.push(`topdown-${b}-${s}`);
}

const ACTION_SPRITE_KEYS = [
  'topdown-villager-chop',
  'topdown-villager-gather',
  'topdown-villager-build',
  'topdown-spearman-attack',
  'topdown-archer-shoot',
  'topdown-cavalry-attack',
  'topdown-rama-shoot',
  'topdown-lakshmana-shoot',
  'topdown-tataka-claw',
  'topdown-subahu-attack',
  'topdown-maricha-shoot',
  'topdown-grunt_enemy-attack',
];

const BIRD_SPRITE_KEYS = ['topdown-bird-1', 'topdown-bird-2', 'topdown-bird-3'];

const SPRITE_KEYS = [
  ...UNIT_DIR_KEYS,
  ...HERO_BOSS_DIR_KEYS,
  ...ACTION_SPRITE_KEYS,
  // V2 tile sprites (no painted ground disc — preferred).
  ...TILE_BUILDING_KEYS,
  // Bala Kanda specific structures.
  'tile-yajna',
  // Demo teaser & boss assets.
  'topdown-tataka-enraged',
  'portrait-tataka',
  'vfx-brahmastra-arrow',
  'icon-brahmastra',
  'icon-indrastra',
  // Rishis (neutral protected NPCs).
  'topdown-rishi',
  'topdown-rishi-standing',
  'topdown-vishwamitra',
  // Ambient wildlife.
  'topdown-deer',
  'topdown-deer-n',
  'topdown-deer-e',
  'sprite-birds-flock',
  ...BIRD_SPRITE_KEYS,
  // V1 portraits (fallback + HUD portrait).
  'building-town-center',
  'building-lanka-citadel',
  'building-house',
  'building-lumber-camp',
  'building-mill',
  'building-mining-camp',
  'building-barracks',
  'building-archery-range',
  'building-stable',
  'building-watchtower',
  // Bust portraits (used in the HUD selection panel).
  'unit-villager',
  'unit-spearman',
  'unit-archer',
  'unit-cavalry',
  'unit-rakshasa-spear',
  // Top-down gameplay sprites (used on the canvas).
  'topdown-villager',
  'topdown-spearman',
  'topdown-archer',
  'topdown-cavalry',
  'topdown-rakshasa-villager',
  'topdown-rakshasa-spear',
  'topdown-rakshasa-archer',
  'topdown-rakshasa-cavalry',
  'resource-tree',
  'resource-berry-bush',
  'resource-gold-vein',
  'resource-stone-vein',
];

const SCENE_KEYS = [
  'title-background',
  'victory-background',
  'defeat-background',
  // Cutscenes (intro story — GPT-scripted, 6 panels).
  'cutscene-01',
  'cutscene-02',
  'cutscene-03',
  'cutscene-04',
  'cutscene-05',
  'cutscene-06',
];

export function preloadSprites(onReady?: () => void) {
  let pending = SPRITE_KEYS.length + SCENE_KEYS.length + TERRAIN_KEYS.length;
  const tick = () => {
    pending--;
    if (pending <= 0 && onReady) onReady();
  };
  for (const key of SPRITE_KEYS) {
    const img = new Image();
    img.crossOrigin = 'anonymous';
    img.onload = () => {
      // Build a chroma-keyed version (cream bg → transparent).
      try {
        KEYED.set(key, chromaKeyCream(img));
      } catch (e) {
        // Canvas tainting can fail on some setups; fall back to the raw image.
        KEYED.set(key, null);
      }
      tick();
    };
    img.onerror = () => { CACHE.set(key, null); tick(); };
    img.src = asset(`sprites/${key}.png`);
    CACHE.set(key, img);
  }
  for (const key of SCENE_KEYS) {
    const img = new Image();
    img.onload = () => tick();
    img.onerror = () => { CACHE.set(key, null); tick(); };
    img.src = asset(`sprites/${key}.png`);
    CACHE.set(key, img);
  }
  // Terrain tile textures — pre-scale to ~256px so they tile densely without
  // looking like one giant 1024px stamp repeated.
  for (const key of TERRAIN_KEYS) {
    const img = new Image();
    img.onload = () => {
      try {
        const target = 256;
        const c = document.createElement('canvas');
        c.width = target;
        c.height = target;
        const cx = c.getContext('2d')!;
        cx.imageSmoothingQuality = 'high';
        cx.drawImage(img, 0, 0, target, target);
        TERRAIN.set(key, c);
      } catch (e) {
        TERRAIN.set(key, null);
      }
      tick();
    };
    img.onerror = () => { TERRAIN.set(key, null); tick(); };
    img.src = asset(`sprites/${key}.png`);
    CACHE.set(key, img);
  }
}

export function getTerrainTile(key: string): HTMLCanvasElement | null {
  return TERRAIN.get(key) ?? null;
}

export function getSprite(key: string): HTMLCanvasElement | HTMLImageElement | null {
  // Prefer the chroma-keyed canvas if available.
  const keyed = KEYED.get(key);
  if (keyed) return keyed;
  const img = CACHE.get(key);
  if (img && img.complete && img.naturalWidth > 0) return img;
  return null;
}

export function getScene(key: string): HTMLImageElement | null {
  const img = CACHE.get(key);
  if (img && img instanceof HTMLImageElement && img.complete && img.naturalWidth > 0) return img;
  return null;
}

// V2 tile sprite (no painted ground disc) — preferred for in-world rendering.
export function buildingTileSpriteKey(typeId: string): string | null {
  typeId = buildingSpriteType(typeId);
  if (typeId === 'town_center') return 'tile-town-center';
  if (typeId === 'town_center_enemy') return 'tile-lanka-citadel';
  if (typeId === 'house' || typeId === 'house_enemy') return 'tile-house';
  if (typeId === 'lumber_camp' || typeId === 'lumber_camp_enemy') return 'tile-lumber-camp';
  if (typeId === 'mill' || typeId === 'mill_enemy') return 'tile-mill';
  if (typeId === 'mining_camp' || typeId === 'mining_camp_enemy') return 'tile-mining-camp';
  if (typeId === 'barracks' || typeId === 'barracks_enemy') return 'tile-barracks';
  if (typeId === 'archery_range' || typeId === 'archery_range_enemy') return 'tile-archery-range';
  if (typeId === 'stable' || typeId === 'stable_enemy') return 'tile-stable';
  if (typeId === 'watchtower') return 'tile-watchtower';
  if (typeId === 'yajna') return 'tile-yajna';
  return null;
}

// Map building typeId → sprite key. Handles both factions sharing a sprite for
// some buildings, and the enemy-only Lanka citadel.
export function buildingSpriteKey(typeId: string): string | null {
  typeId = buildingSpriteType(typeId);
  if (typeId === 'town_center') return 'building-town-center';
  if (typeId === 'town_center_enemy') return 'building-lanka-citadel';
  if (typeId === 'house' || typeId === 'house_enemy') return 'building-house';
  if (typeId === 'lumber_camp' || typeId === 'lumber_camp_enemy') return 'building-lumber-camp';
  if (typeId === 'mill' || typeId === 'mill_enemy') return 'building-mill';
  if (typeId === 'mining_camp' || typeId === 'mining_camp_enemy') return 'building-mining-camp';
  if (typeId === 'barracks' || typeId === 'barracks_enemy') return 'building-barracks';
  if (typeId === 'archery_range' || typeId === 'archery_range_enemy') return 'building-archery-range';
  if (typeId === 'stable' || typeId === 'stable_enemy') return 'building-stable';
  if (typeId === 'watchtower') return 'building-watchtower';
  return null;
}

// HUD-panel portrait (bust).
export function unitSpriteKey(typeId: string): string | null {
  typeId = unitSpriteType(typeId);
  if (typeId === 'villager' || typeId === 'villager_enemy') return 'unit-villager';
  if (typeId === 'spearman') return 'unit-spearman';
  if (typeId === 'spearman_enemy') return 'unit-rakshasa-spear';
  if (typeId === 'archer' || typeId === 'archer_enemy') return 'unit-archer';
  if (typeId === 'cavalry' || typeId === 'cavalry_enemy') return 'unit-cavalry';
  return null;
}

// In-game top-down gameplay sprite (S facing — used when no direction is known).
export function unitTopdownSpriteKey(typeId: string, phase2 = false): string | null {
  typeId = unitSpriteType(typeId);
  switch (typeId) {
    case 'villager': return 'topdown-villager';
    case 'villager_enemy': return 'topdown-rakshasa-villager';
    case 'spearman': return 'topdown-spearman';
    case 'spearman_enemy': return 'topdown-rakshasa-spear';
    case 'archer': return 'topdown-archer';
    case 'archer_enemy': return 'topdown-rakshasa-archer';
    case 'cavalry': return 'topdown-cavalry';
    case 'cavalry_enemy': return 'topdown-rakshasa-cavalry';
    case 'rama': return 'topdown-rama';
    case 'lakshmana': return 'topdown-lakshmana';
    case 'rishi': return 'topdown-rishi';
    case 'vishwamitra': return 'topdown-vishwamitra';
    case 'tataka': return phase2 ? 'topdown-tataka-enraged' : 'topdown-tataka';
    case 'subahu': return 'topdown-subahu';
    case 'maricha': return 'topdown-maricha';
    case 'grunt_enemy': return 'topdown-grunt_enemy';
    case 'deer': return 'topdown-deer';
    default: return null;
  }
}

const warnedActionMisses = new Set<string>();

// Action pose sprite, used while the unit is performing a specific action.
// Returns the sprite key + horizontal-flip flag based on the unit's facing.
export function unitActionSprite(typeId: string, action: 'chop' | 'gather' | 'build' | 'attack' | 'shoot' | 'claw' | 'hunt', facing: number | undefined):
    { key: string; flip: boolean } | null {
  typeId = unitSpriteType(typeId);
  // Map typeId+action to a sprite key. Returns null if no specific sprite exists.
  let key: string | null = null;
  switch (typeId) {
    case 'villager':
      if (action === 'chop') key = 'topdown-villager-chop';
      else if (action === 'gather') key = 'topdown-villager-gather';
      else if (action === 'build') key = 'topdown-villager-build';
      else if (action === 'hunt') key = 'topdown-villager-chop';
      else if (action === 'attack') key = 'topdown-villager-chop';
      break;
    case 'villager_enemy':
      if (action === 'attack') key = 'topdown-grunt_enemy-attack';
      break;
    case 'spearman':
    case 'spearman_enemy':
      if (action === 'attack') key = 'topdown-spearman-attack';
      break;
    case 'archer':
    case 'archer_enemy':
      if (action === 'attack' || action === 'shoot') key = 'topdown-archer-shoot';
      break;
    case 'cavalry':
    case 'cavalry_enemy':
      if (action === 'attack') key = 'topdown-cavalry-attack';
      break;
    case 'rama':
      if (action === 'attack' || action === 'shoot') key = 'topdown-rama-shoot';
      break;
    case 'lakshmana':
      if (action === 'attack' || action === 'shoot') key = 'topdown-lakshmana-shoot';
      break;
    case 'tataka':
      if (action === 'attack' || action === 'claw') key = 'topdown-tataka-claw';
      break;
    case 'subahu':
      if (action === 'attack') key = 'topdown-subahu-attack';
      break;
    case 'maricha':
      if (action === 'attack' || action === 'shoot') key = 'topdown-maricha-shoot';
      break;
    case 'grunt_enemy':
      if (action === 'attack') key = 'topdown-grunt_enemy-attack';
      break;
  }
  if (!key) {
    if (import.meta.env?.DEV && (action === 'attack' || action === 'shoot' || action === 'claw')) {
      const w = warnedActionMisses;
      const tag = `${typeId}+${action}`;
      if (!w.has(tag)) { w.add(tag); console.warn(`[sprites] no action sprite for ${tag} — falling back to directional`); }
    }
    return null;
  }
  // Action sprites are drawn facing east (right). If the unit's facing has a
  // westward component, flip horizontally.
  if (facing === undefined || !Number.isFinite(facing)) return { key, flip: false };
  let a = facing;
  while (a < 0) a += Math.PI * 2;
  while (a >= Math.PI * 2) a -= Math.PI * 2;
  // Flip when facing left (W side: π/2 < a < 3π/2).
  const flip = a > Math.PI / 2 && a < (3 * Math.PI) / 2;
  return { key, flip };
}

// Map typeId to the unit "base" string used in 8-direction sprite names.
function unitBase(typeId: string): string | null {
  switch (typeId) {
    case 'villager': return 'villager';
    case 'villager_enemy': return 'rakshasa-villager';
    case 'spearman': return 'spearman';
    case 'spearman_enemy': return 'rakshasa-spear';
    case 'archer': return 'archer';
    case 'archer_enemy': return 'rakshasa-archer';
    case 'cavalry': return 'cavalry';
    case 'cavalry_enemy': return 'rakshasa-cavalry';
    // Heroes / bosses / wildlife with directional art on disk (preloaded via
    // HERO_BOSS_DIR_KEYS + the explicit deer entries above).
    case 'rama': return 'rama';
    case 'lakshmana': return 'lakshmana';
    case 'tataka': return 'tataka';
    case 'subahu': return 'subahu';
    case 'maricha': return 'maricha';
    case 'grunt_enemy': return 'grunt_enemy';
    case 'deer': return 'deer';
    default: return null;
  }
}

// Which directional variants actually exist on disk per base. Most bases ship
// all four (n/ne/e/se); deer only has n/e. Missing directions fall back to the
// base (S-facing) sprite — getSprite() returns null for never-loaded keys,
// which would otherwise kick the renderer down to its crude flip fallback.
const DEFAULT_DIR_SUFFIXES: readonly string[] = ['n', 'ne', 'e', 'se'];
const DIR_SUFFIXES_BY_BASE: Record<string, readonly string[]> = {
  deer: ['n', 'e'],
};

function dirKeyOrBase(base: string, suffix: string, flip: boolean): { key: string; flip: boolean } {
  const available = DIR_SUFFIXES_BY_BASE[base] ?? DEFAULT_DIR_SUFFIXES;
  if (!available.includes(suffix)) return { key: `topdown-${base}`, flip };
  return { key: `topdown-${base}-${suffix}`, flip };
}

// One of 8 compass directions, derived from a velocity angle.
// Returns the sprite key + whether the sprite should be horizontally flipped.
export function unitDirectionalSprite(typeId: string, angleRad: number | undefined):
    { key: string; flip: boolean } | null {
  const base = unitBase(unitSpriteType(typeId));
  if (!base) return null;
  if (angleRad === undefined || !Number.isFinite(angleRad)) {
    return { key: `topdown-${base}`, flip: false };
  }
  // Canonicalize angle to [0, 2π). 0 = east, π/2 = south.
  // We want 8 buckets centered on the 8 compass directions.
  let a = angleRad;
  while (a < 0) a += Math.PI * 2;
  while (a >= Math.PI * 2) a -= Math.PI * 2;
  // Each bucket is π/4 wide. Bucket center offsets:
  //   0 = E, 1 = SE, 2 = S, 3 = SW, 4 = W, 5 = NW, 6 = N, 7 = NE
  const bucket = Math.round(a / (Math.PI / 4)) % 8;
  switch (bucket) {
    case 0: return dirKeyOrBase(base, 'e',  false);
    case 1: return dirKeyOrBase(base, 'se', false);
    case 2: return { key: `topdown-${base}`, flip: false }; // S = base
    case 3: return dirKeyOrBase(base, 'se', true);  // SW = flip(SE)
    case 4: return dirKeyOrBase(base, 'e',  true);  // W = flip(E)
    case 5: return dirKeyOrBase(base, 'ne', true);  // NW = flip(NE)
    case 6: return dirKeyOrBase(base, 'n',  false);
    case 7: return dirKeyOrBase(base, 'ne', false);
  }
  return null;
}

export function resourceSpriteKey(typeId: string): string | null {
  if (typeId === 'tree') return 'resource-tree';
  if (typeId === 'berry_bush') return 'resource-berry-bush';
  if (typeId === 'gold_vein') return 'resource-gold-vein';
  if (typeId === 'stone_vein') return 'resource-stone-vein';
  return null;
}

// Convert the cream-background sprite to one with the background made
// transparent. Samples the perimeter to pick a robust background color,
// chroma-keys with tolerance bands, then trims the transparent margins so
// the resulting canvas is tightly cropped around the subject (eliminates
// the "halo of padding" that compounded with downscaling caused fringes).
function chromaKeyCream(img: HTMLImageElement): HTMLCanvasElement {
  const W = img.naturalWidth;
  const H = img.naturalHeight;
  const src = document.createElement('canvas');
  src.width = W;
  src.height = H;
  const cx = src.getContext('2d')!;
  cx.drawImage(img, 0, 0);
  const data = cx.getImageData(0, 0, W, H);
  const p = data.data;

  // Sample background along the perimeter (64 points for robustness).
  let r = 0, g = 0, b = 0, n = 0;
  const sample = (x: number, y: number) => {
    const i = (y * W + x) * 4;
    r += p[i]; g += p[i + 1]; b += p[i + 2]; n++;
  };
  for (let i = 0; i < 16; i++) {
    const t = i / 15;
    sample(Math.floor(t * (W - 1)), 0);
    sample(Math.floor(t * (W - 1)), H - 1);
    sample(0, Math.floor(t * (H - 1)));
    sample(W - 1, Math.floor(t * (H - 1)));
  }
  const bgR = r / n, bgG = g / n, bgB = b / n;

  const tol = 48;
  const tolSoft = 82;
  for (let i = 0; i < p.length; i += 4) {
    const dr = p[i] - bgR, dg = p[i + 1] - bgG, db = p[i + 2] - bgB;
    const d = Math.sqrt(dr * dr + dg * dg + db * db);
    if (d < tol) {
      p[i + 3] = 0;
    } else if (d < tolSoft) {
      const a = (d - tol) / (tolSoft - tol);
      p[i + 3] = Math.floor(p[i + 3] * a);
      // Despill: pull the residual cream tint out of the soft edge.
      const k = 1 - a;
      p[i] = Math.max(0, p[i] - bgR * k * 0.5);
      p[i + 1] = Math.max(0, p[i + 1] - bgG * k * 0.5);
      p[i + 2] = Math.max(0, p[i + 2] - bgB * k * 0.5);
    }
  }
  cx.putImageData(data, 0, 0);

  // Auto-crop: find the tight bounding box of non-transparent pixels.
  let minX = W, minY = H, maxX = -1, maxY = -1;
  for (let y = 0; y < H; y++) {
    for (let x = 0; x < W; x++) {
      const a = p[(y * W + x) * 4 + 3];
      if (a > 8) {
        if (x < minX) minX = x;
        if (x > maxX) maxX = x;
        if (y < minY) minY = y;
        if (y > maxY) maxY = y;
      }
    }
  }
  if (maxX < minX) {
    // No subject found (chroma-key removed everything). Fall back to full image.
    minX = 0; minY = 0; maxX = W - 1; maxY = H - 1;
  }
  const cw = maxX - minX + 1;
  const ch = maxY - minY + 1;

  // Pre-scale down to a friendlier render resolution (max edge 256).
  const maxEdge = 256;
  let dstW = cw, dstH = ch;
  if (Math.max(cw, ch) > maxEdge) {
    if (cw >= ch) { dstW = maxEdge; dstH = Math.round(ch * maxEdge / cw); }
    else { dstH = maxEdge; dstW = Math.round(cw * maxEdge / ch); }
  }
  const dst = document.createElement('canvas');
  dst.width = dstW;
  dst.height = dstH;
  const dcx = dst.getContext('2d')!;
  dcx.imageSmoothingEnabled = true;
  dcx.imageSmoothingQuality = 'high';
  dcx.drawImage(src, minX, minY, cw, ch, 0, 0, dstW, dstH);
  return dst;
}
