#!/usr/bin/env node
// Generates illustrative images via OpenAI's gpt-image-2 API and saves them
// to public/sprites/. Quality=low for cost; style prompt prefix is shared so
// the set looks like one art direction. Retries once on transient errors.
//
// Usage: OPENAI_API_KEY=sk-... node scripts/gen-images.mjs [manifest_key]
// If a manifest key is provided, only that one image is generated.

import fs from 'node:fs/promises';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');
const SPRITES_DIR = path.join(ROOT, 'public', 'sprites');
const ENV_PATH = path.join(ROOT, '.env');
const STORY_PATH = path.join(ROOT, 'scripts', 'story.json');

// If scripts/story.json exists (generated by scripts/gen-story.mjs), load its
// cutscene panels and merge them into the manifest, overriding any hard-coded
// cutscene-* entries below.
async function loadStoryPanels() {
  try {
    const raw = await fs.readFile(STORY_PATH, 'utf-8');
    const data = JSON.parse(raw);
    if (!Array.isArray(data.panels)) return [];
    return data.panels.map(p => ({
      key: p.id,            // e.g. "cutscene-01"
      kind: 'scene',
      size: '1536x1024',
      prompt: p.scene_prompt,
    }));
  } catch {
    return [];
  }
}

// Read OPENAI_API_KEY from .env if not already set.
async function loadEnv() {
  if (process.env.OPENAI_API_KEY) return;
  try {
    const data = await fs.readFile(ENV_PATH, 'utf-8');
    for (const line of data.split('\n')) {
      const m = line.match(/^([A-Z_]+)=(.*)$/);
      if (m) process.env[m[1]] = m[2].trim();
    }
  } catch {}
}

// Shared style prefix — keep this stable across all prompts so the asset set
// is visually cohesive. Ramayana-era India, painterly, top-down 3/4 angle for
// buildings, clean light cream background that's easy to chroma-key out.
const STYLE_PREFIX = `Hand-painted digital illustration in the visual style of Age of Empires II HD, but set in ancient Vedic India during the Treta Yuga from the Ramayana epic. Painterly textures with warm earth tones, soft directional lighting from upper-left, slight glow, no harsh shadows. Centered subject on a flat solid pale cream background (#f5e7c8), no border, no text, no UI elements, no signature, no watermark. Subject occupies ~70% of the canvas.`;

// For top-down gameplay unit sprites — small figures viewed almost directly
// from above with slight 3/4 tilt, so they read clearly at 32-48px in-game.
const UNIT_TOPDOWN_PREFIX = `Top-down 3/4 isometric pixel-art-ish hand-painted character sprite for a real-time strategy game in the style of Age of Empires II HD. Subject viewed from above-and-slightly-front so the head is up and the feet are toward the camera. Single figure facing south (toward camera). Crisp silhouette, exaggerated head/shoulders so it reads at small in-game scale. Subject takes up ~55% of the frame, centered. Flat pale cream background (#f5e7c8) with no ground, no shadow, no border, no text, no signature.`;

// Scene backgrounds get a different prefix.
const SCENE_PREFIX = `Hand-painted cinematic concept art in the visual style of an epic Indian mythological video game, depicting the Treta Yuga from the Ramayana. Painterly textures, rich warm color palette, soft golden hour light, atmospheric depth. No text, no UI elements, no watermark, no signature.`;

// Asset manifest. Each entry: { key, prompt, size, kind }
//   kind: 'sprite' uses STYLE_PREFIX, 'scene' uses SCENE_PREFIX.
// Sprites get the cream background so the runtime can knock it out; scenes
// are used full-bleed in the UI.
const MANIFEST = [
  // ----- Bala Kanda hero / boss directional sprites -----
  ...(() => {
    const units = [
      { id: 'rama',     desc: 'Prince Rama from the Ramayana: a young noble warrior with darker Shyama (deep blue-tinged dark) skin tone, wearing a deep blue dhoti with gold jewelry and a saffron sash, long dark hair tied up in a small topknot, calm steady eyes, faint serene smile, holding a great wooden longbow, quiver of arrows on his back' },
      { id: 'lakshmana',desc: 'Prince Lakshmana from the Ramayana: a young warrior with fair golden-brown skin tone (notably lighter than his brother Rama), wearing a saffron-orange dhoti with silver bracelets, dark hair tied up similarly, alert eager expression, holding a curved bow with a short sword at his belt' },
      { id: 'tataka',   desc: 'Tataka, the rakshasi queen: a monstrous female demon with dark blue-grey skin, long matted black hair, fanged mouth, glowing red eyes, crude bone ornaments, tattered hide skirt, clawed hands, towering and imposing' },
      { id: 'subahu',   desc: 'Subahu, a rakshasa brute: a hulking dark-red-skinned demon in heavy black spiked armor with two short horns, savage expression, broad shoulders, wielding a massive iron cleaver' },
      { id: 'maricha',  desc: 'Maricha, a sly rakshasa: a leaner dark-purple-skinned demon in dark leather armor, holding a wicked recurve bow, narrow red-glowing eyes, smirk on fanged mouth, twin curved horns' },
      { id: 'grunt_enemy',desc: 'a rakshasa grunt: wiry dark-red-skinned demon footsoldier with crude spiked iron club, short horns, fanged snarling mouth, ragged loincloth and rusted shoulder plates' },
    ];
    const dirs = [
      { suffix: 'n',  facing: 'directly away from the camera (back of figure visible, back of head, walking away from viewer)' },
      { suffix: 'ne', facing: 'away from the camera and to the right at 45° (back-right three-quarter view, walking up-and-to-the-right)' },
      { suffix: 'e',  facing: 'directly to the right in strict side profile (walking to the right)' },
      { suffix: 'se', facing: 'toward the camera and to the right at 45° (front-right three-quarter view, walking down-and-to-the-right)' },
    ];
    const out = [];
    // Re-render the S facing too so Rama's darker skin gets applied consistently.
    const dirsWithS = [{ suffix: 's', facing: 'directly toward the camera (full front view, walking toward viewer)' }, ...dirs];
    for (const u of units) {
      for (const d of dirsWithS) {
        const key = d.suffix === 's' ? `topdown-${u.id}` : `topdown-${u.id}-${d.suffix}`;
        out.push({
          key, kind: 'unit-topdown', size: '1024x1024',
          prompt: `Top-down 3/4 view of ${u.desc}. The figure is ${d.facing}. Crisp clean silhouette, no shadow on the ground, no painted ground patch — only the figure on flat pale cream background (#f5e7c8). Consistent in size with sibling sprites.`,
        });
      }
    }
    return out;
  })(),

  // ----- Action pose sprites (used while the unit is performing an action) -----
  {
    key: 'topdown-villager-chop',
    kind: 'unit-topdown',
    size: '1024x1024',
    prompt: 'Top-down 3/4 view of an ancient Indian male villager swinging a wood-cutting axe DOWNWARD at a fallen log: white dhoti, saffron sash, brown turban, axe arc visible mid-swing with both hands gripping the haft, body torqued sideways with one foot forward. Strict side profile facing right. Crisp silhouette, no shadow, no ground, on flat pale cream background.',
  },
  {
    key: 'topdown-villager-gather',
    kind: 'unit-topdown',
    size: '1024x1024',
    prompt: 'Top-down 3/4 view of an ancient Indian male villager bent over picking berries from a bush at his feet: white dhoti, saffron sash, brown turban, both hands reaching toward the ground in front of him, basket at his hip. Side profile facing right. Crisp silhouette, no shadow, no ground, on flat pale cream background.',
  },
  {
    key: 'topdown-villager-build',
    kind: 'unit-topdown',
    size: '1024x1024',
    prompt: 'Top-down 3/4 view of an ancient Indian male villager hammering a wooden post with a mallet: white dhoti, saffron sash, brown turban, mallet raised overhead mid-strike, knee bent, focused expression. Side profile facing right. Crisp silhouette, no shadow, no ground, on flat pale cream background.',
  },
  {
    key: 'topdown-spearman-attack',
    kind: 'unit-topdown',
    size: '1024x1024',
    prompt: 'Top-down 3/4 view of an ancient Indian spear infantryman MID-THRUST with a long spear: bronze-rimmed leather lamellar armor, red turban with gold trim, spear extended forward at full reach in his right hand, small round shield up in his left, lunging stance with right leg forward. Side profile facing right. Crisp silhouette, no shadow, no ground, on flat pale cream background.',
  },
  {
    key: 'topdown-archer-shoot',
    kind: 'unit-topdown',
    size: '1024x1024',
    prompt: 'Top-down 3/4 view of an ancient Indian archer DRAWING a curved bamboo bow with arrow nocked: green tunic over brown leather chest piece, brown turban, bow held vertical, right hand pulling the string back to the cheek, left arm fully extended forward gripping the bow, focused eye sighting along the arrow. Side profile facing right. Crisp silhouette, no shadow, no ground, on flat pale cream background.',
  },
  {
    key: 'topdown-cavalry-attack',
    kind: 'unit-topdown',
    size: '1024x1024',
    prompt: 'Top-down 3/4 view of an ancient Indian cavalry warrior on a tan war horse, sabre RAISED HIGH OVERHEAD mid-slash: warrior in blue and gold lamellar armor with golden helmet, body twisted with sabre arm extended up and forward, horse mid-gallop with all four hooves off the ground for an instant. Side profile facing right. Crisp silhouette, no shadow, no ground, on flat pale cream background.',
  },
  {
    key: 'topdown-rama-shoot',
    kind: 'unit-topdown',
    size: '1024x1024',
    prompt: 'Top-down 3/4 view of Prince Rama from the Ramayana DRAWING his great longbow: darker Shyama (deep blue-tinged dark) skin tone, deep blue dhoti, gold jewelry, saffron sash, long dark hair tied in a topknot, bow held vertical at full draw with the arrow string pulled back to his ear, calm focused eyes. Side profile facing right. Crisp silhouette, no shadow, no ground, on flat pale cream background.',
  },
  {
    key: 'topdown-lakshmana-shoot',
    kind: 'unit-topdown',
    size: '1024x1024',
    prompt: 'Top-down 3/4 view of Prince Lakshmana from the Ramayana DRAWING his curved bow: fair golden-brown skin (lighter than his brother Rama), saffron-orange dhoti, silver bracelets, dark hair, alert eager expression, bow at full draw with arrow nocked, body twisted in shooting stance. Side profile facing right. Crisp silhouette, no shadow, no ground, on flat pale cream background.',
  },
  {
    key: 'topdown-tataka-claw',
    kind: 'unit-topdown',
    size: '1024x1024',
    prompt: 'Top-down 3/4 view of Tataka the rakshasi MID-CLAW-STRIKE: monstrous female demon with dark blue-grey skin, long matted black hair flying, fanged mouth wide open, glowing red eyes, both clawed hands swiping forward simultaneously, hide skirt and bone ornaments. Body lunging forward, side profile facing right. Crisp silhouette, no shadow, no ground, on flat pale cream background.',
  },
  {
    key: 'topdown-grunt_enemy-attack',
    kind: 'unit-topdown',
    size: '1024x1024',
    prompt: 'Top-down 3/4 view of a rakshasa grunt SWINGING a spiked iron club: wiry dark-red-skinned demon footsoldier, club arcing in mid-swing over his head with both hands, fanged mouth snarling, ragged loincloth, rusted shoulder plates, leaning into the strike. Side profile facing right. Crisp silhouette, no shadow, no ground, on flat pale cream background.',
  },

  // ----- Ambient wildlife -----
  {
    key: 'topdown-deer',
    kind: 'unit-topdown',
    size: '1024x1024',
    prompt: 'Top-down 3/4 view of an Indian forest deer (chital / spotted deer): tan-brown fur with white spots, slender legs, alert expression with large dark eyes, small antlers on the male. Standing in profile. Crisp silhouette, no shadow, no ground, on flat pale cream background.',
  },
  {
    key: 'topdown-deer-n',
    kind: 'unit-topdown',
    size: '1024x1024',
    prompt: 'Top-down 3/4 view of an Indian forest deer (chital): tan-brown fur with white spots, slender legs, small antlers if male. Walking away from camera (back of deer visible, head turned slightly to glance over shoulder). No shadow, no ground, on flat pale cream background.',
  },
  {
    key: 'topdown-deer-e',
    kind: 'unit-topdown',
    size: '1024x1024',
    prompt: 'Top-down 3/4 view of an Indian forest deer (chital) walking to the right in strict side profile. Tan-brown spotted coat, slender legs in mid-stride, small antlers. No shadow, no ground, on flat pale cream background.',
  },
  {
    key: 'sprite-birds-flock',
    kind: 'sprite',
    size: '1024x1024',
    prompt: 'A small flock of five Indian forest birds (parakeets / mynas) in flight, viewed from above and slightly behind, wings spread mid-flap, vibrant green and yellow plumage with hints of red. Spread across the canvas in a loose V formation. No background — pale cream flat background only.',
  },

  // ----- Bala Kanda specific assets -----
  {
    key: 'tile-yajna',
    kind: 'sprite',
    size: '1024x1024',
    prompt: 'Top-down 3/4 isometric view of the Yajna, a sacred fire altar from the Ramayana epic: a square stone platform with carved Sanskrit-style geometric reliefs around the edges, a vigorous golden-orange flame burning at the center, kusha grass and ghee jars at each corner, faint smoke spiral rising. No grass / ground beneath — only the altar structure on flat pale cream background (#f5e7c8). Sits flat at canvas bottom.',
  },
  {
    key: 'topdown-rama',
    kind: 'unit-topdown',
    size: '1024x1024',
    prompt: 'Top-down 3/4 view of Prince Rama from the Ramayana: a noble young warrior in a deep blue dhoti with gold jewelry, holding a great wooden longbow, long dark hair tied back, calm steady eyes, faint serene smile. Heroic posture, facing the camera. Full-body view.',
  },
  {
    key: 'topdown-lakshmana',
    kind: 'unit-topdown',
    size: '1024x1024',
    prompt: 'Top-down 3/4 view of Prince Lakshmana from the Ramayana: a young warrior in a saffron-orange dhoti with silver bracelets, holding a curved bow, short sword at his belt, dark hair, alert eager expression, similar in size to Rama. Heroic posture, facing camera. Full-body view.',
  },
  {
    key: 'topdown-tataka',
    kind: 'unit-topdown',
    size: '1024x1024',
    prompt: 'Top-down 3/4 view of Tataka, the rakshasi queen from the Ramayana: a monstrous female demon with dark blue-grey skin, long matted black hair, fanged mouth, glowing red eyes, crude bone ornaments around her neck, tattered hide skirt, clawed hands raised, towering and imposing. Sinister, facing camera. Full-body view.',
  },
  {
    key: 'topdown-subahu',
    kind: 'unit-topdown',
    size: '1024x1024',
    prompt: 'Top-down 3/4 view of Subahu, a rakshasa brute son of Tataka: a hulking dark-red-skinned demon in heavy black spiked armor, with a massive cleaver weapon, two small horns on his head, savage expression, broad shoulders. Menacing, facing camera. Full-body.',
  },
  {
    key: 'topdown-maricha',
    kind: 'unit-topdown',
    size: '1024x1024',
    prompt: 'Top-down 3/4 view of Maricha, a sly rakshasa son of Tataka: a leaner dark-purple-skinned demon in dark leather armor, holding a wicked recurve bow, narrow eyes with red glow, smirk on fanged mouth, twin curved horns, fleet stance. Sinister, facing camera. Full-body.',
  },
  {
    key: 'topdown-grunt_enemy',
    kind: 'unit-topdown',
    size: '1024x1024',
    prompt: 'Top-down 3/4 view of a generic rakshasa grunt: a wiry dark-red-skinned demon footsoldier with crude spiked iron club, short horns, fanged snarling mouth, ragged loincloth and rusted shoulder plates, low brow. Aggressive crouched stance, facing camera. Full-body.',
  },

  // ----- Missing action sprites + individual birds -----
  {
    key: 'topdown-subahu-attack',
    kind: 'unit-topdown',
    size: '1024x1024',
    prompt: 'Top-down 3/4 view of Subahu the rakshasa brute MID-CLEAVER-SWING: hulking dark-red-skinned demon in heavy black spiked armor with two short horns, savage roaring expression, massive iron cleaver arcing in mid-swing diagonally across his body, broad shoulders torqued for the strike, one foot forward. Side profile facing right. Crisp silhouette, no shadow, no ground, on flat pale cream background.',
  },
  {
    key: 'topdown-maricha-shoot',
    kind: 'unit-topdown',
    size: '1024x1024',
    prompt: 'Top-down 3/4 view of Maricha the rakshasa archer DRAWING his recurve bow: leaner dark-purple-skinned demon in dark leather armor, holding a wicked recurve bow vertically, right hand pulling the string back to the cheek with arrow nocked, left arm fully extended forward gripping the bow, narrow red-glowing eyes sighting along the arrow, twin curved horns. Side profile facing right. Crisp silhouette, no shadow, no ground, on flat pale cream background.',
  },
  {
    key: 'topdown-bird-1',
    kind: 'sprite',
    size: '1024x1024',
    prompt: 'A single Indian forest bird (parakeet) in flight viewed from above and slightly behind, wings spread mid-flap, vibrant green plumage with a red beak and red wing-tip accents. Crisp silhouette centered on flat pale cream background. No other birds, no ground, no shadow.',
  },
  {
    key: 'topdown-bird-2',
    kind: 'sprite',
    size: '1024x1024',
    prompt: 'A single Indian forest bird (yellow myna) in flight viewed from above and slightly behind, wings spread mid-flap with a downward stroke, golden-yellow plumage with black head and white belly. Crisp silhouette centered on flat pale cream background. No other birds, no ground, no shadow.',
  },
  {
    key: 'topdown-bird-3',
    kind: 'sprite',
    size: '1024x1024',
    prompt: 'A single Indian forest bird (crow) in flight viewed from above, wings spread mid-glide (upward stroke), glossy black plumage. Crisp silhouette centered on flat pale cream background. No other birds, no ground, no shadow.',
  },

  // ----- Rishi (sage) sprite -----
  {
    key: 'topdown-rishi',
    kind: 'unit-topdown',
    size: '1024x1024',
    prompt: 'Top-down 3/4 view of an ancient Indian rishi (forest sage) sitting in meditation: thin elderly man with long white hair, long flowing white beard, weathered serene face with closed eyes, wearing simple saffron-orange robes wrapped around the body, sitting cross-legged in lotus posture, hands resting palms-up on knees, faint golden meditation aura around him. Crisp silhouette, no shadow, no ground patch, on flat pale cream background.',
  },
  {
    key: 'topdown-rishi-standing',
    kind: 'unit-topdown',
    size: '1024x1024',
    prompt: 'Top-down 3/4 view of an ancient Indian rishi (forest sage) standing and looking toward camera: thin elderly man with long white hair flowing past shoulders, long white beard, weathered face, saffron-orange robes draped over one shoulder, wooden walking staff held vertically in one hand, prayer beads in the other. Solemn dignified posture. Crisp silhouette, no shadow, no ground, on flat pale cream background.',
  },
  {
    key: 'topdown-vishwamitra',
    kind: 'unit-topdown',
    size: '1024x1024',
    prompt: 'Top-down 3/4 view of sage Vishwamitra from the Ramayana: tall white-bearded rishi in deeper saffron-orange robes with gold-edged trim, wooden staff topped with a small fire-symbol finial in one hand, prayer beads around the neck, weathered face full of wisdom and authority, faint golden meditation aura. Standing, facing camera. Crisp silhouette, no shadow, no ground patch, on flat pale cream background.',
  },

  // ----- Demo-teaser assets -----
  {
    key: 'teaser-aranya-kanda',
    kind: 'scene',
    size: '1536x1024',
    prompt: 'Hand-painted cinematic concept art for a Ramayana-themed RTS game. Aranya Kanda chapter teaser: Prince Rama in deep blue dhoti and gold jewelry with his longbow, Princess Sita in saffron sari, and Lakshmana in orange dhoti, walking together through a tropical Indian forest in exile, ferns and tall trees around them, dappled sunlight, a golden deer flickers in the distance hinting at Maricha\'s deception. Warm gold-and-emerald palette, painterly oil style. At the bottom-center, a translucent dark band with GOLD SERIF text reading "ARANYA KANDA — THE FOREST EXILE — COMING SOON". Text large and clearly readable.',
  },
  {
    key: 'teaser-kishkindha-kanda',
    kind: 'scene',
    size: '1536x1024',
    prompt: 'Hand-painted cinematic concept art for a Ramayana-themed RTS game. Kishkindha Kanda chapter teaser: a vast Vanara (monkey-warrior) army assembled at the foot of a mountain, with Hanuman in the foreground — a powerful golden-furred ape warrior in red and gold cloth bowing toward Rama in the distance, Sugriva the monkey king beside Hanuman. Sun-drenched valley, warm gold palette. Painterly oil style. At the bottom-center, a translucent dark band with GOLD SERIF text reading "KISHKINDHA KANDA — THE VANARA ALLIES — COMING SOON". Text large and clearly readable.',
  },
  {
    key: 'teaser-yuddha-kanda',
    kind: 'scene',
    size: '1536x1024',
    prompt: 'Hand-painted cinematic concept art for a Ramayana-themed RTS game. Yuddha Kanda chapter teaser: the climactic battle for Lanka — a vast army of Vanara warriors charging across a stone causeway over a raging ocean toward the island fortress of Lanka, which burns red and black with rakshasa defenders on its ramparts. In the foreground, Rama draws his bow at full pull, framed by warriors. Ravana\'s ten-headed silhouette looms in the smoke above the citadel. Dramatic cold blue-and-red palette, epic scale. Painterly oil style. At the bottom-center, a translucent dark band with GOLD SERIF text reading "YUDDHA KANDA — THE SIEGE OF LANKA — COMING SOON". Text large and clearly readable.',
  },
  {
    key: 'topdown-tataka-enraged',
    kind: 'unit-topdown',
    size: '1024x1024',
    prompt: 'Top-down 3/4 view of Tataka the rakshasi in an ENRAGED phase: monstrous female demon with dark blue-grey skin glowing with red veins of fury, long matted black hair flying wildly, fanged mouth roaring open, brilliant red glowing eyes radiating wrath, both clawed hands extended forward, a faint red aura outline around her body, hide skirt and bone ornaments. Towering, mid-roar. Facing camera. Crisp silhouette, no shadow, no ground, on flat pale cream background.',
  },
  {
    key: 'vfx-brahmastra-arrow',
    kind: 'sprite',
    size: '1024x1024',
    prompt: 'A long horizontal divine arrow streaking from left to right, glowing golden-white at the tip with a brilliant comet trail of golden sparks and white energy behind it, sanskrit-style geometric inscriptions faintly visible along the shaft, the arrow itself appears to be made of pure light energy. No background — flat pale cream background only. Horizontal composition, the arrow spans most of the canvas width.',
  },
  {
    key: 'icon-brahmastra',
    kind: 'sprite',
    size: '1024x1024',
    prompt: 'A small square UI icon showing a stylized golden arrow with a glowing comet trail crossing the icon diagonally, sanskrit-style ornament border around the edge in deep gold. Painterly Ramayana style. Centered on flat pale cream background.',
  },
  {
    key: 'icon-indrastra',
    kind: 'sprite',
    size: '1024x1024',
    prompt: 'A small square UI icon showing a stylized blue lightning bolt arrow crossing the icon diagonally, sanskrit-style ornament border around the edge in silver-blue. Painterly Ramayana style. Centered on flat pale cream background.',
  },
  {
    key: 'portrait-tataka',
    kind: 'sprite',
    size: '1024x1024',
    prompt: 'A menacing closeup portrait bust of Tataka the rakshasi from the Ramayana: monstrous female demon with dark blue-grey skin, long matted black hair, fanged snarling mouth, brilliant red glowing eyes, crude bone ornaments around her neck. Head-and-shoulders framing, faintly lit from below. Painterly oil-painting style. On flat pale cream background. Used as a boss-bar portrait.',
  },

  // ----- Cutscene panels (intro story sequence; text rendered directly into the image) -----
  {
    key: 'cutscene-01-treta-yuga',
    kind: 'scene',
    size: '1536x1024',
    prompt: `Cinematic cosmic dawn over ancient India. The clouds part to reveal a celestial scene with subtle radiant deity figures looking down on a vast green plain bordered by snow-capped Himalayan peaks. Painterly, dreamlike, golden hour palette. At the bottom-center of the image, the following text is rendered in elegant gold serif lettering on a translucent dark band: "IN THE TRETA YUGA, RIGHTEOUSNESS WANES." The lettering is large, readable, and clearly legible against a dark band that does not interfere with the scene above. No watermark. No signature.`,
  },
  {
    key: 'cutscene-02-ayodhya',
    kind: 'scene',
    size: '1536x1024',
    prompt: `Sweeping aerial cinematic view of the ancient Indian capital city of Ayodhya at midday: an idealized Vedic-era city of warm sandstone palaces, white temples with golden spires, terracotta-roofed dwellings, surrounded by lush emerald farmlands and the gentle Saryu river curling through. Saffron banners fly from every rooftop. Painterly with rich warm colors. At the bottom-center, the following text in clear gold serif lettering on a translucent dark band: "AYODHYA PROSPERS UNDER KING DASARATHA." Text is large and clearly readable. No watermark. No signature.`,
  },
  {
    key: 'cutscene-03-lanka',
    kind: 'scene',
    size: '1536x1024',
    prompt: `Dark cinematic view of a sinister island fortress at twilight: a black stone citadel topped with spiked iron crenellations, smoke rising from braziers, monstrous rakshasa demon figures patrolling the ramparts. The sea around it is dark and choppy under a blood-red sky. Painterly, ominous, high contrast. At the bottom-center, the following text in clear blood-red serif lettering on a translucent dark band: "BUT IN THE SOUTH, LANKA STIRS." Text is large and clearly readable. No watermark. No signature.`,
  },
  {
    key: 'cutscene-04-vishwamitra',
    kind: 'scene',
    size: '1536x1024',
    prompt: `Cinematic forest clearing at dawn: the ancient sage Vishwamitra (a tall white-bearded rishi in saffron robes) stands beside a young Prince Rama (a noble youth in princely blue tunic and gold jewelry, holding a great wooden bow). Both look toward the rising sun streaming through tall trees. A sacred fire burns between them. Painterly, deeply atmospheric. At the bottom-center, the following text in clear gold serif lettering on a translucent dark band: "THE SAGE VISHWAMITRA CALLS UPON RAMA." Text is large and clearly readable. No watermark. No signature.`,
  },
  {
    key: 'cutscene-05-call-to-arms',
    kind: 'scene',
    size: '1536x1024',
    prompt: `Heroic wide shot at sunset: Prince Rama stands at the head of an Ayodhya war party — bronze-armored Bhata spearmen, green-tunic Dhanvi archers, golden-armored Ashvarudha cavalry on horses. They face away from the camera toward a distant dark fortress on the horizon. Saffron banners catch the wind. Painterly, epic, dramatic light. At the bottom-center, the following text in clear gold serif lettering on a translucent dark band: "LEAD AYODHYA. DEFEND DHARMA." Text is large and clearly readable. No watermark. No signature.`,
  },

  // ----- Scene backgrounds (used full-bleed in UI panels) -----
  {
    key: 'title-background',
    kind: 'scene',
    size: '1536x1024',
    prompt: 'Wide cinematic landscape: dawn breaks over an ancient Indian forest valley. In the foreground, a peaceful ashram of warm wooden buildings with thatched roofs and saffron banners sits beside a slow river. In the middle distance, sacred trees and a small stone shrine. In the far distance, dark mountains and a smoldering rakshasa stronghold across the valley. Mist clings to the river. Painterly brushstrokes, warm golden palette accented by deep emerald foliage, suggesting Ramayana-era splendor.',
  },
  {
    key: 'victory-background',
    kind: 'scene',
    size: '1536x1024',
    prompt: 'Triumphant scene: a victorious Ayodhya army stands on a hilltop at sunset, banners aloft, looking down at a destroyed and burning rakshasa fortress in the distance. Warm orange sky, painterly clouds, golden light catching armor and spearpoints. A stylized image of Lord Rama silhouetted in the foreground holding his bow. Painterly Indian mythological style.',
  },
  {
    key: 'defeat-background',
    kind: 'scene',
    size: '1536x1024',
    prompt: 'Somber scene: a ruined Ayodhya settlement at dusk, broken wooden structures smoldering, fallen saffron banners. In the background, dark menacing rakshasa figures stand victorious on a hill. Cool blue-gray palette with red glow from fires. Painterly Indian mythological style, moody and dramatic.',
  },

  // ----- Building tile sprites v2 (no ground disc, tight crop) -----
  // The v2 sprites are intended to drop into in-game tile positions without a
  // painted ground beneath them — just the structure itself on cream so the
  // game's terrain texture shows through under the building.
  {
    key: 'tile-town-center',
    kind: 'sprite',
    size: '1024x1024',
    prompt: 'Top-down 3/4 angle isometric view of an ancient Indian ashram building ONLY: a large square wooden hall with a steep tiered pyramidal roof of red terracotta tiles, stone foundation walls, ornate gold finial spire at the top, saffron banners. No grass, no soil patch, no shadow on the ground, no painted ground disc — only the building structure itself on a flat pale cream background (#f5e7c8). The bottom edge of the building should be flat / level / aligned with the bottom of where the building sits.',
  },
  {
    key: 'tile-lanka-citadel',
    kind: 'sprite',
    size: '1024x1024',
    prompt: 'Top-down 3/4 angle isometric view of a dark rakshasa citadel ONLY: large dark stone fortress with spiked black iron crenellations, twisted spire of dark red stone, demon skull motif on the central spire, black banners with red rakshasa eye emblem, sinister and imposing. No grass, no soil, no shadow, no painted ground — only the structure on a flat pale cream background (#f5e7c8). Building base sits flat at the bottom of the canvas.',
  },
  {
    key: 'tile-house',
    kind: 'sprite',
    size: '1024x1024',
    prompt: 'Top-down 3/4 angle isometric view of a small ancient Indian village hut ONLY: thatched conical roof, mud-and-stone walls, small wooden door, a clay pot beside the entrance. No grass, no soil, no shadow, no painted ground disc — only the hut structure on a flat pale cream background (#f5e7c8). The building footprint sits flat at the canvas bottom.',
  },
  {
    key: 'tile-lumber-camp',
    kind: 'sprite',
    size: '1024x1024',
    prompt: 'Top-down 3/4 angle isometric view of a forest lumber processing camp ONLY: wooden frame structure with stacks of logs to one side, an axe on a tree stump, a wooden wagon, sawdust pile. No grass, no soil, no shadow, no painted ground disc — only the camp items on a flat pale cream background (#f5e7c8). Items sit flat at canvas bottom.',
  },
  {
    key: 'tile-mill',
    kind: 'sprite',
    size: '1024x1024',
    prompt: 'Top-down 3/4 angle isometric view of an ancient Indian granary mill ONLY: a circular stone building with domed roof, sacks of grain stacked outside, a stone grinding wheel visible. No grass, no soil, no shadow, no painted ground — only the building on a flat pale cream background (#f5e7c8). Building sits flat.',
  },
  {
    key: 'tile-mining-camp',
    kind: 'sprite',
    size: '1024x1024',
    prompt: 'Top-down 3/4 angle isometric view of a mining camp ONLY: stone hut beside a small quarry pit, pickaxes leaning against a rock, piles of gold and stone nuggets nearby, mine cart with wheels. No grass, no soil, no shadow, no painted ground — only the camp on a flat pale cream background (#f5e7c8). Sits flat.',
  },
  {
    key: 'tile-barracks',
    kind: 'sprite',
    size: '1024x1024',
    prompt: 'Top-down 3/4 angle isometric view of an ancient Indian military barracks ONLY: a long rectangular wooden building with peaked roof, sword racks visible through open archways, training dummies in front courtyard, saffron banner with sword emblem. No grass, no soil, no shadow, no painted ground disc — only the building on a flat pale cream background (#f5e7c8). Building footprint flat at canvas bottom.',
  },
  {
    key: 'tile-archery-range',
    kind: 'sprite',
    size: '1024x1024',
    prompt: 'Top-down 3/4 angle isometric view of an ancient Indian archery range ONLY: open-sided wooden pavilion with archery targets at the back, racks of bows and arrows along the side. No grass, no soil, no shadow, no painted ground disc — only the building on a flat pale cream background (#f5e7c8). Building footprint flat at canvas bottom.',
  },
  {
    key: 'tile-stable',
    kind: 'sprite',
    size: '1024x1024',
    prompt: 'Top-down 3/4 angle isometric view of an ancient Indian cavalry stable ONLY: long wooden building with two arched stall openings, a horse visible inside one stall, hay bales beside the entrance, saffron banner with horse emblem. No grass, no soil, no shadow, no painted ground — only the building on a flat pale cream background (#f5e7c8). Sits flat.',
  },
  {
    key: 'tile-watchtower',
    kind: 'sprite',
    size: '1024x1024',
    prompt: 'Top-down 3/4 angle isometric view of an ancient Indian stone watchtower ONLY: tall square stone tower with crenellated battlements on top, narrow arrow slits, a saffron banner flying from the peak. No grass, no soil, no shadow, no painted ground — only the tower on a flat pale cream background (#f5e7c8). Tower sits flat at canvas bottom.',
  },

  // ----- Building portraits (cream bg for chroma-key) -----
  {
    key: 'building-town-center',
    kind: 'sprite',
    size: '1024x1024',
    prompt: 'Top-down 3/4 angle isometric view of an ancient Indian ashram: a large square wooden hall with a steep tiered pyramidal roof of red terracotta tiles, stone foundation, ornate gold finial spire on top, and saffron banners. Surrounded by a low stone perimeter wall with corner towers. Lord Rama\'s emblem (a bow) decorates the central spire. Centered on flat pale cream background.',
  },
  {
    key: 'building-house',
    kind: 'sprite',
    size: '1024x1024',
    prompt: 'Top-down 3/4 angle isometric view of a small ancient Indian village hut: thatched conical roof, mud-and-stone walls, small wooden door, a clay pot beside the entrance. Charming and humble. Centered on flat pale cream background.',
  },
  {
    key: 'building-lumber-camp',
    kind: 'sprite',
    size: '1024x1024',
    prompt: 'Top-down 3/4 angle isometric view of a forest lumber processing camp: wooden frame structure with stacks of logs to one side, an axe on a tree stump, sawdust on the ground, a wooden wagon. Rustic, busy. Centered on flat pale cream background.',
  },
  {
    key: 'building-mill',
    kind: 'sprite',
    size: '1024x1024',
    prompt: 'Top-down 3/4 angle isometric view of an ancient Indian granary mill: a circular stone building with a domed roof, sacks of grain stacked outside, a stone grinding wheel visible. Painterly. Centered on flat pale cream background.',
  },
  {
    key: 'building-mining-camp',
    kind: 'sprite',
    size: '1024x1024',
    prompt: 'Top-down 3/4 angle isometric view of a mining camp: stone hut beside a quarry pit, pickaxes leaning against a rock, piles of gold and stone nuggets nearby, mine cart with wheels. Centered on flat pale cream background.',
  },
  {
    key: 'building-barracks',
    kind: 'sprite',
    size: '1024x1024',
    prompt: 'Top-down 3/4 angle isometric view of an ancient Indian military barracks: a long rectangular wooden building with a peaked roof, sword racks visible through open archways, training dummies in the front courtyard, a saffron banner with a sword emblem. Centered on flat pale cream background.',
  },
  {
    key: 'building-archery-range',
    kind: 'sprite',
    size: '1024x1024',
    prompt: 'Top-down 3/4 angle isometric view of an ancient Indian archery range: open-sided wooden pavilion with archery targets at the back, racks of bows and arrows along the side, a small sand training area in front. Centered on flat pale cream background.',
  },
  {
    key: 'building-stable',
    kind: 'sprite',
    size: '1024x1024',
    prompt: 'Top-down 3/4 angle isometric view of an ancient Indian cavalry stable: long wooden building with two arched stall openings, a horse visible inside one stall, hay bales beside the entrance, a saffron banner with a horse emblem. Centered on flat pale cream background.',
  },
  {
    key: 'building-watchtower',
    kind: 'sprite',
    size: '1024x1024',
    prompt: 'Top-down 3/4 angle isometric view of an ancient Indian stone watchtower: tall square stone tower with crenellated battlements on top, narrow arrow slits, a saffron banner flying from the peak. Centered on flat pale cream background.',
  },
  {
    key: 'building-lanka-citadel',
    kind: 'sprite',
    size: '1024x1024',
    prompt: 'Top-down 3/4 angle isometric view of an evil rakshasa citadel: large dark stone fortress with spiked black iron crenellations, twisted spire roof of dark red stone, demon skull motif on the central spire, black banners with red rakshasa eye emblem. Sinister and imposing. Centered on flat pale cream background.',
  },

  // ----- Unit portraits (cream bg) -----
  {
    key: 'unit-villager',
    kind: 'sprite',
    size: '1024x1024',
    prompt: 'Portrait of an ancient Indian villager: a young man in white dhoti and saffron cloth wrap, holding a wood-cutting axe over one shoulder, friendly determined expression, painterly style. Bust composition centered. Flat pale cream background.',
  },
  {
    key: 'unit-spearman',
    kind: 'sprite',
    size: '1024x1024',
    prompt: 'Portrait of an ancient Indian spear infantryman (Bhata): a warrior in bronze-rimmed leather armor and red turban, holding a long iron-tipped spear vertically, serious resolute expression. Painterly style. Bust composition centered. Flat pale cream background.',
  },
  {
    key: 'unit-archer',
    kind: 'sprite',
    size: '1024x1024',
    prompt: 'Portrait of an ancient Indian archer (Dhanvi): a warrior in a green tunic and brown leather chest piece, holding a curved bamboo bow, quiver of arrows on his back, focused expression. Painterly style. Bust composition centered. Flat pale cream background.',
  },
  {
    key: 'unit-cavalry',
    kind: 'sprite',
    size: '1024x1024',
    prompt: 'Portrait of an ancient Indian cavalry warrior (Ashvarudha): a noble warrior in blue and gold lamellar armor, golden helmet, mounted on a tan war horse, holding a curved sabre raised, fierce expression. Painterly style. Centered. Flat pale cream background.',
  },
  {
    key: 'unit-rakshasa-spear',
    kind: 'sprite',
    size: '1024x1024',
    prompt: 'Portrait of a rakshasa spear warrior: a fierce humanoid demon with dark red skin, sharp fangs, glowing eyes, wearing black spiked armor with a horned helmet, holding a wicked black iron spear. Sinister. Painterly style. Bust composition centered. Flat pale cream background.',
  },

  // ----- 8-direction unit sprites (N, NE, E, SE; W/NW/SW are flips at runtime) -----
  // Direction conventions:
  //   N  = back of figure visible, walking away from camera
  //   NE = three-quarter back-right, walking up-and-to-the-right
  //   E  = strict right profile, walking to the right
  //   SE = three-quarter front-right, walking down-and-to-the-right
  //   (S is the original "topdown-*" sprite, already exists)
  ...(() => {
    const units = [
      { id: 'villager',         desc: 'an ancient Indian male villager in white dhoti, saffron sash, brown turban, holding a wood-cutting axe at his side' },
      { id: 'spearman',         desc: 'an ancient Indian spear infantryman in bronze-rimmed leather lamellar armor, blue tunic, red turban with gold trim, holding a long iron-tipped spear and small round shield' },
      { id: 'archer',           desc: 'an ancient Indian archer in green tunic and brown leather chest piece, brown turban, holding a curved bamboo bow vertically, quiver of arrows on his back' },
      { id: 'cavalry',          desc: 'an ancient Indian cavalry warrior in blue and gold lamellar armor with a golden helmet, mounted on a tan war horse with red and gold caparison, holding a curved sabre' },
      { id: 'rakshasa-villager',desc: 'a rakshasa worker, dark red-skinned humanoid demon in tattered black wraps, holding a simple iron tool, sharp fangs visible' },
      { id: 'rakshasa-spear',   desc: 'a rakshasa spear warrior, dark red-skinned demon in black spiked lamellar armor with a horned iron helmet, holding a wicked black iron spear and small black shield' },
      { id: 'rakshasa-archer',  desc: 'a rakshasa archer, dark red-skinned demon in dark purple wraps and black leather armor, holding a wicked recurve bow, black-fletched arrows in a back quiver' },
      { id: 'rakshasa-cavalry', desc: 'a rakshasa cavalry rider on a black dire horse with red eyes, dark armored demon in spiked black armor and horned helmet, holding a curved black sabre' },
    ];
    const dirs = [
      { suffix: 'n',  facing: 'directly away from the camera (we see the back of the figure, the back of the head/helmet, the back of armor or robe). Walking forward away from viewer.' },
      { suffix: 'ne', facing: 'away from the camera and to the right at a 45° angle (we see the back-right three-quarter view, with right shoulder forward and head turned slightly so right ear is visible). Walking up-and-to-the-right.' },
      { suffix: 'e',  facing: 'directly to the right (strict side profile — the figure is in pure profile, one shoulder pointing at camera, the other at the right edge). Walking to the right.' },
      { suffix: 'se', facing: 'toward the camera and to the right at a 45° angle (we see the front-right three-quarter view, face turned slightly right). Walking down-and-to-the-right toward the viewer.' },
    ];
    const entries = [];
    for (const u of units) {
      for (const d of dirs) {
        entries.push({
          key: `topdown-${u.id}-${d.suffix}`,
          kind: 'unit-topdown',
          size: '1024x1024',
          prompt: `Top-down 3/4 view of ${u.desc}. The figure is ${d.facing} Crisp clean silhouette, no shadow on the ground, no painted ground patch — only the figure on flat pale cream background. The figure is centered and consistent in size with sibling sprites in this set.`,
        });
      }
    }
    return entries;
  })(),

  // ----- Top-down gameplay unit sprites (S facing — generated earlier as topdown-*) -----
  {
    key: 'topdown-villager',
    kind: 'unit-topdown',
    size: '1024x1024',
    prompt: 'Top-down 3/4 view of an ancient Indian male villager: white dhoti, saffron sash, brown turban, holding a small wood-cutting axe at his side. Friendly working pose, facing camera. Dark hair visible from above.',
  },
  {
    key: 'topdown-spearman',
    kind: 'unit-topdown',
    size: '1024x1024',
    prompt: 'Top-down 3/4 view of an ancient Indian spear infantryman: bronze-rimmed leather lamellar armor over a blue tunic, red turban with gold trim, holding a long iron-tipped spear vertically beside him, small round shield in the other hand. Battle stance, facing camera.',
  },
  {
    key: 'topdown-archer',
    kind: 'unit-topdown',
    size: '1024x1024',
    prompt: 'Top-down 3/4 view of an ancient Indian archer: green tunic over brown leather chest piece, brown turban, holding a curved bamboo bow vertically, quiver of arrows on the back visible behind one shoulder. Alert stance, facing camera.',
  },
  {
    key: 'topdown-cavalry',
    kind: 'unit-topdown',
    size: '1024x1024',
    prompt: 'Top-down 3/4 view of an ancient Indian cavalry warrior mounted on a tan horse: warrior wears blue and gold lamellar armor with a golden conical helmet, holds a curved sabre raised; horse with red and gold caparison. Facing camera, mid-stride. The entire mounted unit centered.',
  },
  {
    key: 'topdown-rakshasa-villager',
    kind: 'unit-topdown',
    size: '1024x1024',
    prompt: 'Top-down 3/4 view of a rakshasa worker: dark red-skinned humanoid demon in tattered black wraps, simple iron tool. Hunched menacing pose facing camera. Sharp fangs visible.',
  },
  {
    key: 'topdown-rakshasa-spear',
    kind: 'unit-topdown',
    size: '1024x1024',
    prompt: 'Top-down 3/4 view of a rakshasa spear warrior: dark red-skinned demon in black spiked lamellar armor with a horned iron helmet, holding a wicked black iron spear and small black shield. Fierce stance, facing camera.',
  },
  {
    key: 'topdown-rakshasa-archer',
    kind: 'unit-topdown',
    size: '1024x1024',
    prompt: 'Top-down 3/4 view of a rakshasa archer: dark red-skinned demon in dark purple wraps and black leather armor, holding a wicked recurve bow vertically, black-fletched arrows in a back quiver. Sinister stance, facing camera.',
  },
  {
    key: 'topdown-rakshasa-cavalry',
    kind: 'unit-topdown',
    size: '1024x1024',
    prompt: 'Top-down 3/4 view of a rakshasa cavalry rider on a black dire horse with red eyes: dark armored demon rider in spiked black armor and horned helmet, holding a curved black sabre. Menacing, facing camera, mid-stride. Full mounted unit centered.',
  },

  // ----- Terrain textures (seamlessly tileable) -----
  {
    key: 'terrain-grass',
    kind: 'sprite',
    size: '1024x1024',
    prompt: 'Top-down view of a lush green grass field, ancient India landscape, painterly oil-painting style with visible brushstrokes. Rich variations in green hue, scattered tiny wildflowers (white, yellow, pink), small clumps of taller grass, occasional pebbles. Seamlessly tileable — no visible edges or borders. No central focal point — uniform distribution. Subtle warm sunlight from upper-left. No background, no text, no signature.',
  },
  {
    key: 'terrain-dirt',
    kind: 'sprite',
    size: '1024x1024',
    prompt: 'Top-down view of a dry trodden dirt path / packed earth surface, ancient Indian terrain, painterly oil-painting style. Warm tan and brown hues with subtle cracks, scattered tiny pebbles, dried leaves, sand variation. Seamlessly tileable — no visible edges or borders. No central focal point. Subtle warm sunlight from upper-left. No background, no text, no signature.',
  },
  {
    key: 'terrain-water',
    kind: 'sprite',
    size: '1024x1024',
    prompt: 'Top-down view of calm shallow river water surface in an ancient Indian landscape, painterly oil-painting style. Soft blue-green hues with gentle visible ripples, occasional light reflections, no current or wave directionality. Seamlessly tileable — no visible edges or borders. No central focal point. No background, no text, no signature.',
  },
  {
    key: 'terrain-forest-floor',
    kind: 'sprite',
    size: '1024x1024',
    prompt: 'Top-down view of a forest floor under tropical Indian trees, painterly oil-painting style. Dark mossy ground with fallen leaves (green, yellow, brown), small mushrooms, exposed roots, scattered pebbles, dappled shadow. Seamlessly tileable — no visible edges or borders. No central focal point. No background, no text, no signature.',
  },
  {
    key: 'terrain-rock',
    kind: 'sprite',
    size: '1024x1024',
    prompt: 'Top-down view of a rocky stone ground surface, ancient Indian highlands, painterly oil-painting style. Grey weathered stone with cracks, small chunks of broken rock, hints of moss in crevices. Seamlessly tileable — no visible edges or borders. No central focal point. No background, no text, no signature.',
  },

  // ----- AoE-style UI ornaments -----
  {
    key: 'ui-panel-bg',
    kind: 'sprite',
    size: '1024x1024',
    prompt: 'Hand-painted texture of an ancient stone tablet surface, warm sandstone tan with subtle weathering, faint geometric chisel marks at the edges, no central focal point, painterly and seamless. No text, no border lines, no signature. Just the stone surface, viewed straight-on.',
  },
  {
    key: 'ui-panel-frame',
    kind: 'sprite',
    size: '1536x1024',
    prompt: 'Hand-painted decorative frame border in the style of ancient Indian temple carvings: ornate gold and brass corners with lotus motifs, hand-chiseled stone edge with floral relief carving along the top and bottom, blank center area. The frame fills the canvas with the central rectangular area transparent / blank (showing the cream background through it). Symmetrical, painterly, warm tones.',
  },
  {
    key: 'ui-scroll-banner',
    kind: 'sprite',
    size: '1536x1024',
    prompt: 'Hand-painted unfurled parchment scroll with ornate gold-leaf endcaps and silk tassels, slightly aged paper texture, blank center for text. The scroll is horizontal and fills the canvas. Painterly Ramayana-era Indian style. No text on the scroll itself. Just the parchment surface, framed by the rolled-up ends.',
  },
  {
    key: 'ui-button-stone',
    kind: 'sprite',
    size: '1024x1024',
    prompt: 'Hand-painted stylized stone button: weathered tan sandstone block with carved gold-leaf border, slight bevel from raised edges catching sunlight from upper-left. Blank center face for text. Painterly, ancient Indian temple architecture style. Square format. The button fills 80% of the canvas.',
  },

  // ----- UI icons -----
  {
    key: 'icon-wood',
    kind: 'sprite',
    size: '1024x1024',
    prompt: 'Single small icon: a bundle of three chopped wood logs tied with rope, painterly style. Centered on flat pale cream background. Used as a UI resource icon.',
  },
  {
    key: 'icon-food',
    kind: 'sprite',
    size: '1024x1024',
    prompt: 'Single small icon: a wicker bowl filled with red berries and grains, painterly style. Centered on flat pale cream background. Used as a UI resource icon.',
  },
  {
    key: 'icon-gold',
    kind: 'sprite',
    size: '1024x1024',
    prompt: 'Single small icon: a small pile of glittering gold coins and a gold ingot, painterly style. Centered on flat pale cream background. Used as a UI resource icon.',
  },
  {
    key: 'icon-stone',
    kind: 'sprite',
    size: '1024x1024',
    prompt: 'Single small icon: three rough grey stone blocks stacked, painterly style. Centered on flat pale cream background. Used as a UI resource icon.',
  },
  {
    key: 'icon-population',
    kind: 'sprite',
    size: '1024x1024',
    prompt: 'Single small icon: three stylized human silhouettes (a villager, a man, a warrior) standing together in saffron and gold, painterly style. Centered on flat pale cream background. Used as a UI population icon.',
  },
  {
    key: 'emblem-ayodhya',
    kind: 'sprite',
    size: '1024x1024',
    prompt: 'Heraldic emblem of the Ayodhya kingdom: a stylized golden sun with rays, a small bow-and-arrow at the center, on a saffron banner with gold trim. Symmetrical, painterly. Centered on flat pale cream background.',
  },
  {
    key: 'emblem-lanka',
    kind: 'sprite',
    size: '1024x1024',
    prompt: 'Sinister heraldic emblem of the Lanka kingdom: a black demon eye with red iris and curved horns above, on a black banner with blood-red trim. Symmetrical, ominous, painterly. Centered on flat pale cream background.',
  },

  // ----- Resource illustrations -----
  {
    key: 'resource-tree',
    kind: 'sprite',
    size: '1024x1024',
    prompt: 'Top-down 3/4 view of a single lush tropical Indian tree: rich green canopy of broad leaves, thick brown trunk with textured bark, suggesting a banyan or sal tree. Painterly. Centered on flat pale cream background.',
  },
  {
    key: 'resource-berry-bush',
    kind: 'sprite',
    size: '1024x1024',
    prompt: 'Top-down 3/4 view of a wild berry bush: dense green foliage dotted with clusters of vibrant red berries. Painterly. Centered on flat pale cream background.',
  },
  {
    key: 'resource-gold-vein',
    kind: 'sprite',
    size: '1024x1024',
    prompt: 'Top-down 3/4 view of a small outcropping of rocks streaked with bright gold ore veins, glimmering in the light. Painterly. Centered on flat pale cream background.',
  },
  {
    key: 'resource-stone-vein',
    kind: 'sprite',
    size: '1024x1024',
    prompt: 'Top-down 3/4 view of a cluster of grey boulders, suggesting a small stone quarry, with chunks of cut stone nearby. Painterly. Centered on flat pale cream background.',
  },
];

async function generate({ key, kind, size, prompt }) {
  const prefix =
    kind === 'scene' ? SCENE_PREFIX :
    kind === 'unit-topdown' ? UNIT_TOPDOWN_PREFIX :
    STYLE_PREFIX;
  const fullPrompt = `${prefix}\n\n${prompt}`;
  const body = {
    model: 'gpt-image-2',
    prompt: fullPrompt,
    quality: 'low',
    size,
    n: 1,
  };
  const res = await fetch('https://api.openai.com/v1/images/generations', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${process.env.OPENAI_API_KEY}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(body),
  });
  if (!res.ok) {
    const txt = await res.text();
    throw new Error(`API ${res.status}: ${txt.slice(0, 400)}`);
  }
  const data = await res.json();
  const b64 = data.data?.[0]?.b64_json;
  if (!b64) throw new Error(`No image returned: ${JSON.stringify(data).slice(0, 200)}`);
  const buf = Buffer.from(b64, 'base64');
  const out = path.join(SPRITES_DIR, `${key}.png`);
  await fs.writeFile(out, buf);
  return { key, bytes: buf.length, path: out };
}

async function main() {
  await loadEnv();
  if (!process.env.OPENAI_API_KEY) {
    console.error('Missing OPENAI_API_KEY (looked in env and .env)');
    process.exit(1);
  }
  await fs.mkdir(SPRITES_DIR, { recursive: true });

  // Merge in story-driven cutscene prompts if available. They override any
  // hard-coded cutscene-* entries from the static MANIFEST.
  const storyPanels = await loadStoryPanels();
  const storyKeys = new Set(storyPanels.map(p => p.key));
  const baseManifest = MANIFEST.filter(m => !storyKeys.has(m.key));
  const fullManifest = [...storyPanels, ...baseManifest];

  const filter = process.argv[2];
  const items = filter ? fullManifest.filter(m => m.key === filter || m.key.includes(filter)) : fullManifest;
  if (items.length === 0) {
    console.error('No matching manifest entries.');
    process.exit(1);
  }

  // Skip ones that already exist (idempotent re-runs).
  const todo = [];
  for (const item of items) {
    try {
      await fs.access(path.join(SPRITES_DIR, `${item.key}.png`));
      console.log(`[skip] ${item.key} (already exists)`);
    } catch {
      todo.push(item);
    }
  }
  console.log(`Generating ${todo.length} image(s)…`);

  // Sequential to be polite to the API and to keep cost predictable.
  const results = { ok: [], fail: [] };
  for (const item of todo) {
    const t0 = Date.now();
    try {
      const r = await generate(item);
      const dt = ((Date.now() - t0) / 1000).toFixed(1);
      console.log(`[ok]   ${item.key}  ${(r.bytes / 1024).toFixed(0)}kb  ${dt}s`);
      results.ok.push(item.key);
    } catch (e) {
      console.warn(`[warn] ${item.key}: ${e.message}`);
      // One retry.
      try {
        const r = await generate(item);
        const dt = ((Date.now() - t0) / 1000).toFixed(1);
        console.log(`[ok]   ${item.key}  (retry)  ${(r.bytes / 1024).toFixed(0)}kb  ${dt}s`);
        results.ok.push(item.key);
      } catch (e2) {
        console.error(`[fail] ${item.key}: ${e2.message}`);
        results.fail.push(item.key);
      }
    }
  }

  console.log(`\nDone. ${results.ok.length} ok, ${results.fail.length} failed.`);
  if (results.fail.length > 0) {
    console.log('Failed:', results.fail.join(', '));
    process.exit(1);
  }
}

main().catch((e) => { console.error(e); process.exit(1); });
